== 5. Asset locators

Assets can be fetched from different location thanks to _asset locators_. This section describes how it works and the available _asset locators_.

=== 5.1. Introducing asset locators

An _asset locator_ (or _locator_ to simplify the language) is defined as follows:

* A location key, used as an identifier in the bundle definitions
* An associated location that may be processed, depending on the locator
* A flag indicating whether the asset should be cached or not

=== 5.2 Asset caching

Depending on the locator, Dandelion generates the right URL to serve the asset directly from the location where it lives. 

For example, all assets present in the webapp directory are defaultly served by the webapp itself. In this case, Dandelion will just process the given location by prepending the context path and no caching is necessary.

However, an asset stored in the classpath for example, cannot be served directly by the webapp. Instead, in such a case, Dandelion fetches its content and stores it in the configured <<9-asset-caching, cache system>>, with a particular cache key. Later, the generated link pointing to this asset will be served by the `DandelionServlet`, the role of which is to retrieve the content from the cache system and serve it.

See the <<9-asset-caching, asset caching section>> for more information.

=== 5.3. Locations resolution strategy

The most obvious case is to configure an asset with a single location.

.jquery.json
[source, json]
----
{
  "assets": [
    {
      "locations": {
        "remote": "//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.js",
      }
    }
  ]
}
----

In the above bundle, Dandelion will always use the single `remote` location to fetch the jQuery asset.

In cases where multiple locations are configured for a single asset, Dandelion uses a particular strategy to resolve them. It simply reads the <<opt-asset.locations.resolution.strategy, `asset.locations.resolution.strategy`>> option from your configuration file and tests in a particular order if a location is present for a specified set of locators.

The default resolution strategy is defined as follows:

 asset.locations.resolution.strategy = webapp, webjar, jar, remote

Here is what happens:

. First checks if a `webapp` location key is specified. If so, the corresponding location will be selected and processed
. Then, if a `webjar` location key is defined, the corresponding location will be selected and processed
. Then, the same a `jar` location key
. And finally with a `remote` location key
. If none of the above is specified, an exception will be thrown.

Assuming the following bundle:

.jquery.json
[source, json]
----
{
  "assets": [
    {
      "locations": {
        "webapp" : "/assets/js/jquery.js",
        "remote": "//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.js",
      }
    }
  ]
}
----

In such a case, thanks to the default resolution strategy, Dandelion will first prioritize the `webapp` location.

TIP: Combined with <<10-profiles, profiles>>, this feature is powerful enough to handle multiple locations in multiple environments.

=== 5.4. Built-in locators

Dandelion comes with a couple of built-in locators. They are all listed below.

==== 5.4.1. `webapp` locator

The `webapp` locator should be used whenever you need to load an asset stored in the web application directory.

|===
| *Location key* | `webapp`

| *Corresponding value* | Relative path to the web application root directory

| *Caching forced* | No
|===

[discrete]
==== Example

Assuming the following project structure:

.Example with a Maven project
[source, xml]
----
your-project
|__ src
   |__ main
      |__ webapp
         |__ assets
            |__ js
               |__ application.js
----

The asset declaration should look like:

.dandelion/bundle.json
[source, json]
----
{
  "assets": [
    {
      "locations": {
        "webapp": "/assets/js/application.js"
      }
    }
  ]
}
----

Client-side, Dandelion will generate the following link:

[source, html]
----
<script src="/[contextPath]/assets/js/application.js"></script>
----

==== 5.2.2. `classpath` locator

The `classpath` should be used whenever you need to load an asset stored in the classpath.

|===
| *Location key* | `classpath`

| *Corresponding value* | Absolute name of the asset (no leading "/", as it internally uses `ClassLoader.getResourceAsStream()`)

| *Caching forced* | Yes
|===

[discrete]
==== Example

Assuming the following project structure:

.Example with a Maven project
[source, xml]
----
your-project
|__ src
   |__ main
      |__ resources
         |__ js
            |__ application.js
----

The asset declaration should look like:

.dandelion/bundle.json
[source, json]
----
{
  "assets": [
    {
      "locations": {
        "classpath": "js/application.js"
      }
    }
  ]
}
----

Client-side, Dandelion will generate the following link:

[source, html]
----
<script src="/[contextPath]/dandelion-assets/[cacheKey]/application.js"></script>
----

==== 5.2.3. `remote` locator

The `remote` locator should be used whenever you need to load an asset hosted externally, e.g. on a http://en.wikipedia.org/wiki/Content_delivery_network[Content Delivery Network].

|===
| *Location key* | `remote`

| *Corresponding value* | URL of the asset (protocal-relative URLs such as _//domain/foo.js_ are supported)

| *Caching forced* | No
|===

[discrete]
==== Example

Assuming the following asset declaration:

.dandelion/bundle.json
[source, json]
----
{
  "assets": [
    {
      "locations": {
        "remote": "//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.js"
      }
    }
  ]
}
----

Client-side, Dandelion will generate the following link:

[source, html]
----
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.js"></script>
----

==== 5.2.4. `jar` locator

The `jar` locator should be used whenever you need to load an asset stored inside a JAR, under the `META-INF/resources` folder. 

|===
| *Location key* | `jar`

| *Corresponding value* | Relative path to the `META-INF/resources` folder

| *Caching forced* | No. Dandelion takes profit of the Servlet 3.x feature that consists of serving from the application web context root all assets placed under the `META-INF/resources` directory of any JAR placed in `WEB-INF/lib`. In such a case, the asset is not cached but directly served from the JAR instead.
|===

[discrete]
==== Example

Dandelion-Datatables internally uses this locator to serve almost all DataTables-related assets.

For example, the _datatables-core_ project contains the following tree structure:

.datatables-core project
[source, xml]
----
datatables-core
|__ src
   |__ main
      |__ resources
         |__ META-INF
            |__ resources
               |__ dandelion
                  |__ datatables
                     |__ ajax
                        |__ reload.js
----

According to the above structure, the corresponding bundle should look like:

[source, json]
----
{
  ...
  "assets": [
    {
      "locations": {
         "jar": "dandelion/datatables/ajax/reload.js"
      }
    }
  ]
}
----

Client-side, Dandelion will generate the following link:

[source, html]
----
<script src="/[contextPath]/dandelion/datatables/ajax/reload.js"></script>
----

==== 5.2.5. `webjar` locator

This locator is bundled in the _dandelion-webjars_ extra since it brings a new dependency to the https://github.com/webjars/webjars-locator[webjars-locator] project. This project is internally used by the _webjar locator_ to locate assets inside http://www.webjars.org/[WebJars].

.New dependency required
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.github.dandelion</groupId>
  <artifactId>dandelion-webjars</artifactId>
  <version>{ddl-version}</version>
</dependency>
----

The `webjar` locator should be used whenever you need to load an asset stored inside a http://www.webjars.org/[WebJar].

|===
| *Location key* | `webjar`

| *Corresponding value* | Name of the asset (path excluded but extension included)

| *Caching forced* | No
|===

[discrete]
==== Example

Assuming that the _bootstrap-2.3.0.jar_ is present in the classpath, the bundle definition should look like:

[source, json]
----
{
  "assets": [
    {
      "locations": {
        "webjars": "bootstrap.css"
      }
    }
  ]
}
----

Client-side, Dandelion will generate the following link:

[source, html]
----
<link rel="stylesheet" href="/[contextPath]/webjars/bootstrap/2.3.0/css/bootstrap.css" />
----

==== 5.2.6. `api` locator

The `api` locator should be used for generated assets, i.e. assets whose content is programmaticaly generated.

|===
| *Location key* | `api`

| *Corresponding value* | Name given to the asset

| *Caching forced* | Yes
|===

This locator is a bit particular since it reads the content of the asset from a special parameter stored inside the `AssetRequestContext`.

This parameter:

* must be stored under the `ApiLocator.API_CONTENT_PARAM` key
* must be a class that implements `AssetContentGenerator` and where the `getAssetContent()` method must return the content of the asset

[discrete]
==== Example

Dandelion-Datatables internally uses this locator to delegate the asset generation to a custom generator.

Below is the main Dandelion-Datatables bundle:

.src/main/resources/dandelion/datatables/ddl-dt.json
[source, json]
----
{
  ...
  "assets": [
    {
      ...
      "name": "dandelion-datatables",
      "locations": {
        "api": "dandelion-datatables.js"
      }
    }
  ]
}
----

TODO
In the above bundle, an asset called `dandelion-datatables` will be used to store a particular entry in the `AssetRequestContext` object, which is the main user-side entry point for manipulating the bundle graph associated to the current `HttpServletRequest`.

TODO
To such a key will be associated a specific entry: 
has a delegated content. It basically means that a delegate object must return the content to be injected into this asset.

TODO
This can be done thanks to the `AssetRequestContext` object which is the main user-side entry point for manipulating the bundle graph associated to the current `HttpServletRequest`.

[source, java]
----
JQueryContentGenerator javascriptGenerator = new JQueryContentGenerator(...);

AssetRequestContext
  .get(request) // <1>
  .addBundles("ddl-dt") // <2>
  .addParameter("dandelion-datatables", ApiLocator.API_CONTENT_PARAM, javascriptGenerator, false); // <3>
----
<1> `get(request)` returns the `AssetRequestContext` object
<2> `addBundles("ddl-dt")` just adds the given bundle to the `AssetRequestContext`. This way, all assets specified in this bundle will be loaded into the page
<3> `addParameter(...)` fills the request context with a particular entry: `dandelion-datatables` <--> `<ApiLocator.API_CONTENT_PARAM, javascriptGenerator>`. 

Finally, Dandelion will generate the following link:

[source, html]
----
<script src="/[contextPath]/dandelion-assets/[cacheKey]/dandelion-datatables-xxx.js"></script>
----

=== 5.3. Plugging-in your own asset locator

Like most parts of the framework, you can use your own asset locator thanks to the SPI mechanism.

In order to plug-in your own locator, just follow these steps:

. Create a class that extends `AbstractAssetLocator` (you can directly implement the `AssetLocator` interface but you better use the abstract class)

+
[source, java]
----
package com.foo.asset.locator.impl;

public class MyLocator extends AbstractAssetLocator {

   @Override
   public String getLocationKey() {
      return "a-new-location-key";
   }

   @Override
   public boolean isCachingForced() {
      return false;
   }

   @Override
   public String doGetLocation(AssetStorageUnit asu, HttpServletRequest request) {
      return "the location of the asset";
   }

   @Override
   protected String doGetContent(String location, Map<String, Object> parameters, HttpServletRequest request) {
      return "the content of the asset";
   }
}
----

. In the `META-INF/services` folder, create a text file (UTF-8 encoded) using the following convention:

+
.Example with a Maven project
[source, xml]
----
project-root
|__ src
   |__ main
      |__ resources
         |__ META-INF
            |__ services
               |__ com.github.dandelion.core.asset.locator.spi.AssetLocator
----
 
+
Inside this file, just add the fully qualified name of your own implementation. For example:

 com.foo.asset.locator.impl.MyLocator

And that's all! Dandelion, thanks to the SPI mechanism, will automatically pick up your implementation on the next restart.
