== 7. Asset processors

=== 7.1. Introducing asset processors

Dandelion provides some processors intended to be applied on assets. This section introduces major concepts around these processors.

==== 7.1.1. Definition

An _asset processor_ (or _processor_ to simplify the language) is defined as follows:

* A processor key, used as an identifier
* A type of asset to process, such as *js* or *css*

Most of the existing processors are used to minify assets.

Dandelion-Core already provides some built-in processors which are auto-configured depending on the active profile. See below for more information.

NOTE: In upcoming releases, more processors will be provided, allowing to process more CSS and JavaScript languages such as http://coffeescript.org/[CoffeeScript] or http://sass-lang.com/[Sass].

==== 7.1.2. Configuring asset processors

Asset processors are configured via the <<opt-asset.processors, `asset.processors`>> configuration option. You just need to define a comma-separated list of processor keys to enable the corresponding processors on all assets.

For example, the default value is in the `prod` profile is `cssurlrewriting,jsmin,cssmin`. This means that by default, the corresponding processors will be applied sequentially on all assets, depending on their type.

==== 7.1.3. Enabling asset processing

The asset processing is enabled thanks to the <<opt-asset.minification, `asset.minification`>> configuration option.

Set it to `true` to minify all assets using the configured processors. Set it to `false` and all assets will be served as-is.

==== 7.1.4. Asset caching and naming strategy

It is worth noting that:

* *Asset naming*: the min keyword is automatically appended to the asset name, just before its extension.

+
For example, an original asset called `app.css` will be served as `app-[MD5HASH].min.css`. 

* *Asset caching*: once processed, all assets will be cached in the configured cache system, and then served by the `DandelionServlet`.

=== 7.2. Built-in processors

Dandelion comes with some built-in processors. They can be summarised in the following table:

|===
|Processor key |Compatible asset type
|cssmin |CSS
|cssurlrewriting |CSS
|jsmin |JS
|===

==== 7.2.1. CSSMin

This processor uses a https://github.com/andyroberts/csscompressor[fork] of the Yahoo's YUI Compressor authored by http://www.andy-roberts.net/coding/csscompressor[Andrew Roberts].


===== Example

Before:

[source, css]
----
.myclassA {
  font-style: bold;
}

/* Some comments */
.myclassB {
  background-color: rgb(51,102,153);
}

.myclassC {
  color: #AABBCC;
}

/* An empty rule */
.myClassD {
}
----

After:

[source, css]
----
.myclassA{font-style:bold}.myclassB{background-color:#369}.myclassC{color:#ABC}
----

==== 7.2.3. CSS URL rewriting

This processor processes all relative paths in CSS and replaces them by absolute ones according to the number of occurrences of ".." counted.

===== Example

Before:

The CSS file is loaded from:

 http://cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/css/jquery.dataTables.css

and contains:

[source, css]
----
.paginate_enabled_previous { 
  background: url('../images/back_enabled.png');
}
----
 
After, the line will be replaced by: 
 
[source, css]
----
.paginate_enabled_previous { 
  background: url('http://cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/images/back_enabled.png');
}
----

==== 7.2.4. JsMin

This processor is based on a translation from C to Java of jsmin.c published by http://www.crockford.com/javascript/jsmin.html[Douglas Crockford].

[discrete]
===== Example

Before:

[source, javascript]
----
// is.js

// (c) 2001 Douglas Crockford
// 2001 June 3


// is

// The -is- object is used to identify the browser.  Every browser edition
// identifies itself, but there is no standard way of doing it, and some of
// the identification is deceptive. This is because the authors of web
// browsers are liars. For example, Microsoft's IE browsers claim to be
// Mozilla 4. Netscape 6 claims to be version 5.

var is = {
    ie:      navigator.appName == 'Microsoft Internet Explorer',
    java:    navigator.javaEnabled(),
    ns:      navigator.appName == 'Netscape',
    ua:      navigator.userAgent.toLowerCase(),
    version: parseFloat(navigator.appVersion.substr(21)) ||
             parseFloat(navigator.appVersion),
    win:     navigator.platform == 'Win32'
}
is.mac = is.ua.indexOf('mac') >= 0;
if (is.ua.indexOf('opera') >= 0) {
    is.ie = is.ns = false;
    is.opera = true;
}
if (is.ua.indexOf('gecko') >= 0) {
    is.ie = is.ns = false;
    is.gecko = true;
}
----

After:

[source, javascript]
----
var is={ie:navigator.appName=='Microsoft Internet Explorer',java:navigator.javaEnabled(),ns:navigator.appName=='Netscape',ua:navigator.userAgent.toLowerCase(),version:parseFloat(navigator.appVersion.substr(21))||parseFloat(navigator.appVersion),win:navigator.platform=='Win32'}
is.mac=is.ua.indexOf('mac')>=0;if(is.ua.indexOf('opera')>=0){is.ie=is.ns=false;is.opera=true;}
if(is.ua.indexOf('gecko')>=0){is.ie=is.ns=false;is.gecko=true;}
----

=== 7.3. Plugging-in your own processor

In order to plug-in your own asset processor, just follow these steps:

. Create a class that extends `AbstractAssetProcessor` and annotate it with `@CompatibleAssetType`

+
[source, java]
----
package com.foo.asset.processor.impl;

@CompatibleAssetType(types = AssetType.css) // <1>
public class MyProcessor extends AbstractAssetProcessor {

   @Override
   public String getProcessorKey() {
      return "myprocessorkey";
   }

   @Override
   public void doProcess(Asset asset, Reader reader, Writer writer) throws Exception {
      ...
   }
}
----
<1> Specify the asset type for which the processor is compatible

. In the `META-INF/services` folder, create a text file (UTF-8 encoded) using the following convention:

+
.Example with a Maven project
[source, xml]
----
project-root
|__ src
   |__ main
      |__ resources
         |__ META-INF
            |__ services
               |__ com.github.dandelion.core.asset.processor.AssetProcessor
----
 
+
Inside this file, just add the fully qualified name of your own implementation. For example:

 com.foo.asset.processor.impl.MyProcessor

. Finally, update the <<opt-asset.processors, `asset.processors`>> configuration option by including your processor. For example:

+
[source, properties]
----
asset.processors=cssurlrewriting,jsmin,cssmin,myprocessorkey
----
