== 8. Bundle loaders

Bundles fall into two categories: *vendor* and *user*.
All *vendor* bundles are supposed to reference vendor assets or libraries such as jQuery.
*User* bundles are supposed to reference all other assets, in particular all assets developed and maintained for the deployed application.

This disctinction is important because Dandelion doesn't behave in the same way with *vendor* and *user* bundles, especially in terms of versioning, processing and loading. 

=== 8.1. Introducing bundle loaders

The main goals of bundle loaders are:

* to scan for bundle definitions (all `\*.json` files) in the classpath, *vendor* and *user* ones
* to map each of the loaded files into a comprehensive format and feed the <<4-2-building-a-bundle-graph, bundle graph>>

=== 8.2. Built-in loader

Dandelion-Core comes with one built-in loader: `DandelionBundleLoader`. This bundle loader is focused on both `classpath_root/dandelion/vendor` and `classpath_root/dandelion` folders, respectively for *vendor* and *user* bundles.

=== 8.3. Loading order

Each bundle loader has several purposes, the most important of which is to load bundle in a particular order:

. First, all loaders are invoked to scan for *vendor bundles*, with the `DandelionBundleLoader` always acting in last

. Then, all loaders are invoked again but to scan for *user bundles*, again with the `DandelionBundleLoader` in last

This particular order ensures that vendor bundles are always loaded in first and may be easily overriden by user ones.

==== Example

Let's assume that two bundle loaders are registered in the Dandelion context: `DandelionBundleLoader` and `CustomBundleLoader` (`classpath_root/dandelion/custom/vendor` / `classpath_root/dandelion/custom`). At startup, Dandelion-Core will apply the following sequence:

. the `CustomBundleLoader` will scan for *vendor* bundles in its configured scanning path: `classpath_root/dandelion/custom/vendor`
. the `DandelionBundleLoader` will scan for *vendor* bundles in its configured scanning path: `classpath_root/dandelion/vendor`
. the `CustomBundleLoader` will scan for *user* bundles in its configured scanning path: `classpath_root/dandelion/custom`
. the `DandelionBundleLoader` will scan for *user* bundles in its configured scanning path: `classpath_root/dandelion`

=== 8.4. Plugging-in your own bundle loader

You may wish to write an extension that uses its own bundle loader, e.g. if you wish to scan for bundles somewhere else than in the classpath. Let's see here how to do it.

Dandelion intensively uses the http://docs.oracle.com/javase/tutorial/sound/SPI-intro.html[Service Provider Interface] mechanism introduced in Java 6.

So, in order to plug-in your own bundle loader, just follow these steps:

. Create a class that extends `AbstractBundleLoader`

+
[source, java]
----
package com.foo.bundle.loader.impl;

public class MyBundleLoader extends AbstractBundleLoader {

   private static final Logger LOG = LoggerFactory.getLogger(MyBundleLoader.class);

   public static final String LOADER_NAME = "custom-loader";
   public static final String SCANNING_PATH = "dandelion/custom-path";

   public DatatableBundleLoader(Context context, boolean isStandalone) {
      super(context, isStandalone);
   }

   @Override
   public String getName() {
      return LOADER_NAME; <1>
   }

   @Override
   protected Logger getLogger() {
      return LOG;
   }

   @Override
   public String getScanningPath() {
      return SCANNING_PATH;
   }
}
----
<1> The loader name is used for logging purpose only

. In the `META-INF/services` folder, create a text file (UTF-8 encoded) using the following convention:

+
.Example with a Maven project
[source, xml]
----
project-root
|__ src
   |__ main
      |__ resources
         |__ META-INF
            |__ services
               |__ com.github.dandelion.core.bundle.loader.BundleLoader
----

+
Inside this file, just add the fully qualified name of your own implementation. For example:

 com.foo.bundle.loader.impl.MyBundleLoader

And that's all! Thanks to the SPI mechanism, Dandelion will automatically pick up your implementation and add it to the active bundle loaders on the next server restart.
