== 1. Introducing Dandelion-Core

=== 1.1. What is Dandelion-Core?

Dandelion-Core is the foundation of the Dandelion framework. It is mainly focused on static asset management (such as JavaScript or CSS), it includes the whole mechanics necessary to help developing web applications in JVM-based environments.

=== 1.2. Features overview

Major topics covered by Dandelion-Core are:

* asset organization in bundles, with several possible asset locations such as `webapp`, `webjar`, `cdn`, ...
* asset processing, such as minification
* asset caching, both server and client side
* asset versioning, manual or automatic through different strategies
* asset generation, allowing to extend the core with components

All these topics will be addressed in this document.

=== 1.3. Overall architecture

Dandelion-Core is mainly based on a http://docs.oracle.com/javaee/6/api/javax/servlet/Filter.html[Filter] which dynamically injects static assets into http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponse.html[HttpServletResponse]s, that is - HTML pages. Dandelion-Core is therefore considered as a _runtime solution_ (as opposed to _build time solutions_ provided by other frameworks/libraries).

Dandelion-Core reads a set of bundle definitions, either embedded within existing components or directly provided by end-users, and represented in different formats (such as JSON or XML). Once these bundle definitions consumed, Dandelion-Core builds a directed acyclic graph of bundles (or _bundles graph_ later in this document) and traverses this graph as soon as one or more bundles are requested by the end-user.

Since Dandelion-Core have full control over the static assets, many actions can be performed such as asset versioning, browser caching, and many more.
