== 9. Profiles

TIP: Pending

Dandelion profiles provide a way to segregate parts of your configuration and make it only available in certain environments.

In order to activate a profile, specify the following System property in the server startup script:

 -Ddandelion.profile.active=[profileName]

=== 9.1. Built-in profiles

All <<12-configuration-options, configuration options>> are created with two values, one for the built-in `dev` profile, another for the `prod` one. Each of these profiles are described below.

==== 9.1.1. `dev` profile

The main goal of the `dev` profile is to accelerate the development. As such, it is *active by default*.

Here follow some of the features enabled with the `dev` profile:

* the Dandelion debugger is accessible, see the <<12-debugger, debugger section>> for more information
* bundles can be reloaded on-demand thanks to a specific request parameter, see TODO
* a particular caching policy is applied thus preventing assets from being cached by browsers
* all generated assets are pretty-printed, thus easing debugging

See the <<appendix-c-configuration-options-reference, configuration options reference>> for the complete list of dev values.

TIP: This profile can be activated thanks to different aliases: `dev` and `development`. 

==== 9.1.2. `prod` profile

The `prod` profile is focused both on performance and security. That is why it should be active in a production environment.

Here follow some of the features enabled with the `prod` profile:

* specific HTTP headers are set in order to optimize load times (performance) 
* asset minification is enabled (performance) 
* GZIP compression is enabled for compatible MIME types (performance)
* automatic versioning is enabled (performance) 
* the debugger is no longer accessible (security)
* bundle can't be reloaded any longer (security)

See the <<appendix-c-configuration-options-reference, configuration options reference>> for the complete list of prod values.

TIP: This profile can be activated thanks to different aliases: `prod` and `production`. 

=== 9.2. Custom profiles

You can of course define your own profiles. It is as simple as creating a new properties file under the `classpath_root/dandelion` folder, with a specific name: `dandelion_[profileName].properties`

WARNING: All options not explicitely declared in your own profile file will be read from the built-in `dev` profile.
			
.Example with a Maven project
[source, xml]
----
project-root
|__ src
   |__ main
      |__ resources
         |__ dandelion
            |__ dandelion_[profileName].properties 
----

Then, just activate it using the right system property:

 -Ddandelion.profile.active=[profileName]

Note that you can also define your own properties in profiles and use them in bundle definitions with the following syntax:

 %PROPERTY%

This is particularly useful when your application is to be deployed in multiple environments.

==== Example

Consider the two following profiles: `qa` and `prod`.

.dandelion/dandelion_qa.properties
[source, xml]
----
# Dandelion options here
asset.minification=false
tool.gzip=false
tool.asset.pretty.printing=true

# Custom property here
media.server=http://qa-media.company.com/
----

.dandelion/dandelion_prod.properties
[source, xml]
----
# Dandelion options here
asset.minification=true
tool.gzip=true
tool.asset.pretty.printing=false

# Custom property here
media.server=https://prod-media.company.com/
----

You can then make use of the custom property in your bundle definitions with the following format: `%property%`

.any-bundle.json
[source, json]
----
{  
  "assets":[  
    {  
      ...,
      "locations":{  
        "remote":"%media.server%/js/app.js"
      }
    }
  ]
}
----

Dandelion will perform the variable substitution as soon as the application server starts.